# BLE Mesh service

namespace py thrift_types.ble_mesh_config_service
namespace java thrift_types.ble_mesh_config_service

include "bluetooth_common.thrift"

enum MeshConfigServicePropertyID {
  RESERVED_FOR_FUTURE_USE     = 0x00, # ID 0 could be used for service discovery, e.g. return last ID code
  ALWAYS_ON                   = 0x01,
  DIMMABLE                    = 0x02,
  MINIMUM_DIM_LEVEL           = 0x03,
  MAXIMUM_DIM_LEVEL           = 0x04,
  MOTION_LOW_THRESHOLD        = 0x05,
  MOTION_HIGH_THRESHOLD       = 0x06,
  STATUS_LIGHT_MAX_BRIGHTNESS = 0x07,
  UNICAST_ADDRESS_FORWARDING  = 0x08,
  MOTION_TO_TRIGGER_ON        = 0x09,
  MOTION_TO_TRIGGER_OFF       = 0x0A,
  MOTION_SCORE                = 0x0B,
  MOTION_DETECTED             = 0x0C,
  TEMPERATURE                 = 0x0D,
  UUID                        = 0x0E,
  FIRMWARE_VERSION            = 0x0F,
  API_VERSION                 = 0x10,
  CURRENT_ZERO_CROSS          = 0x11,
  BREAK_DIMMING               = 0x12,
  POWER                       = 0x13,
  POWER_THRESHOLD             = 0x14,
  BREAK_CIRCUIT               = 0x15,
  CURRENT_SENSE_ADC_DATA      = 0x16,
  DEVICE_REVISION             = 0x17,
  ERROR_STATUS                = 0x18,
  DOUBLE_TAP_ENABLED          = 0x19,
  SWITCH_LOAD_TYPE            = 0x1A,
  UNICAST_FORWARDING_GESTURES = 0x1B,
  CAPTOUCH_AND_LOAD_CONNECTED = 0x1C,
  AMPS_IN_MA                  = 0x1D,
  AMPS_SAFE_MAX_THRESHOLD     = 0x1E,
  TEMP_SAFE_MAX_THRESHOLD     = 0x1F,
  MOTION_MIN_SMPLS_BTW_UPDATE = 0x20,
  DBG_LAST_CS_RESULT_STATUS   = 0x21,
  DBG_COMPUTED_ZERO_POINT     = 0x22,
  DBG_CYCLES_SINCE_ZC_SUCCESS = 0x23,
  TUNE_MAX_DEVIATION_IDL_ZERO = 0x24,
  TUNE_ZC_NUM_PT_FOR_NOISE_REDUCTION   = 0x25,
  TUNE_MAX_DEV_BETWEEN_RUNS            = 0x26,
  REBOOT                      = 0x27,
  ENABLE_FWID_PACKET_BROADCAST= 0x28,
  DFU_LAST_TRANSFER_STATE     = 0x29,
  DFU_LAST_RX_RESPONSE        = 0x2A,
  DFU_END_TRANSFER_REASON     = 0x2B,
  DFU_LAST_RX_PACKET          = 0x2C,
  HARDWARE_REVISION           = 0x2D,
  CAPTOUCH_BTN00_TUNING_PARAM = 0x2E,
  CAPTOUCH_SLD00_TUNING_PARAM = 0x2F,
  PROXY_HAS_ACTIVE_CONNS      = 0x30,
  PROXY_DISCONNECT_ALL        = 0x31,
  REPLAY_CACHE_CLEAR          = 0x32,
  REPLAY_CACHE_GET_NUM_ELEM   = 0x33,
  REPLAY_CACHE_GET_CUR_IV     = 0x34,
  REPLAY_CACHE_SET_GET_ELEM_IDX = 0x35,
  REPLAY_CACHE_GET_ELEM_SRC   = 0x36,
  REPLAY_CACHE_GET_ELEM_SEQ   = 0x37,
  REPLAY_CACHE_GET_ELEM_IV    = 0x38,
  DFU_RELAY_ENABLED           = 0x40,
  DFU_RELAY_APP_ID            = 0x41,
  DFU_RELAY_APP_VERSION       = 0x42,
  DBG_BUF_SET_NEXT_TRIGGER    = 0x43,
  DBG_BUF_AWAITING_NEXT_TRIGGER       = 0x44,
  DBG_BUF_CUR_CONTENTS_TRIGGER        = 0x45,
  DBG_BUF_SET_READ_CHUNK_IDX  = 0x46,
  DBG_BUF_GET_CHUNK           = 0x47,
  USE_COMPACT_COMM_PROTOCOL_FOR_PUBLISHING_VARIABLE = 0x48,
}

const map<MeshConfigServicePropertyID, bluetooth_common.ServicePropertySpec> CONFIG_SERVICE_PROPERTY_SPECS = {
  MeshConfigServicePropertyID.ALWAYS_ON: {
    "property_id": MeshConfigServicePropertyID.ALWAYS_ON,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_ALWAYS_ON,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DIMMABLE: {
    "property_id": MeshConfigServicePropertyID.DIMMABLE,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_DIMMABLE,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.MINIMUM_DIM_LEVEL: {
    "property_id": MeshConfigServicePropertyID.MINIMUM_DIM_LEVEL,
    "property_size": 2,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1000,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_MIN_DIM_LEVEL,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.MAXIMUM_DIM_LEVEL: {
    "property_id": MeshConfigServicePropertyID.MAXIMUM_DIM_LEVEL,
    "property_size": 2,
    "default_value": 1000,
    "min_value": 0,
    "max_value": 1000,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_MAX_DIM_LEVEL,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.MOTION_LOW_THRESHOLD: {
    "property_id": MeshConfigServicePropertyID.MOTION_LOW_THRESHOLD,
    "property_size": 1,
    "default_value": 20,
    "min_value": 0,
    "max_value": 100,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_MOTION_LOW_THRESHOLD,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.MOTION_HIGH_THRESHOLD: {
    "property_id": MeshConfigServicePropertyID.MOTION_HIGH_THRESHOLD,
    "property_size": 1,
    "default_value": 70,
    "min_value": 0,
    "max_value": 100,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_MOTION_HIGH_THRESHOLD,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.STATUS_LIGHT_MAX_BRIGHTNESS: {
    "property_id": MeshConfigServicePropertyID.STATUS_LIGHT_MAX_BRIGHTNESS,
    "property_size": 2,
    "default_value": 1000,
    "min_value": 0,
    "max_value": 1000,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_STATUS_LIGHT_MAX_DIM,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.UNICAST_ADDRESS_FORWARDING: {
    "property_id": MeshConfigServicePropertyID.UNICAST_ADDRESS_FORWARDING,
    "property_size": 2,
    "default_value": 0,
    "min_value": 0,
    "max_value": 65535,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_UNICAST_FORWARD_ADDR,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.MOTION_TO_TRIGGER_ON: {
    // This property has been deprecated
    "property_id": MeshConfigServicePropertyID.MOTION_TO_TRIGGER_ON,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.MOTION_TO_TRIGGER_OFF: {
    // This property has been deprecated
    "property_id": MeshConfigServicePropertyID.MOTION_TO_TRIGGER_OFF,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.MOTION_SCORE: {
    "property_id": MeshConfigServicePropertyID.MOTION_SCORE,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 100,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.MOTION_DETECTED: {
    "property_id": MeshConfigServicePropertyID.MOTION_DETECTED,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.PUBLISH_ON_DELTA,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.TEMPERATURE: {
    "property_id": MeshConfigServicePropertyID.TEMPERATURE,
    "property_size": 2,
    "default_value": 32767,
    "min_value": -32768,
    "max_value": 32767,
    "property_type": bluetooth_common.MeshPropertyDataType.INT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.UUID: {
    "property_id": MeshConfigServicePropertyID.UUID,
    "property_size": 16,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8_ARRAY,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.FIRMWARE_VERSION: {
    "property_id": MeshConfigServicePropertyID.FIRMWARE_VERSION,
    "property_size": 8, // SoftDevice (2 bytes) + Bootloader (2 bytes) + App (4 bytes)
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8_ARRAY,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.API_VERSION: {
    // This property is unused
    "property_id": MeshConfigServicePropertyID.API_VERSION,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 255,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.CURRENT_ZERO_CROSS: {
    "property_id": MeshConfigServicePropertyID.CURRENT_ZERO_CROSS,
    "property_size": 2,
    "default_value": 0xFFFF,
    "min_value": 0,
    "max_value": 0xFFFF,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.BREAK_DIMMING: {
    // This property has been deprecated
    "property_id": MeshConfigServicePropertyID.BREAK_DIMMING,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.POWER: {
    "property_id": MeshConfigServicePropertyID.POWER,
    "property_size": 2,
    "default_value": 0xFFFF, // units in 1/10 of a watt
    "min_value": 0,
    "max_value": 65535,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.POWER_THRESHOLD: {
    // This property has been deprecated
    "property_id": MeshConfigServicePropertyID.POWER_THRESHOLD,
    "property_size": 2,
    "default_value": 0, // units in 1/10 of a watt
    "min_value": 0,
    "max_value": 65535,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.BREAK_CIRCUIT: {
    // This property has been deprecated
    "property_id": MeshConfigServicePropertyID.BREAK_CIRCUIT,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 3,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.CURRENT_SENSE_ADC_DATA: {
    // This property has been deprecated
    "property_id": MeshConfigServicePropertyID.CURRENT_SENSE_ADC_DATA,
    "property_size": 256, // 128 values of 2 byte adc readings
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8_ARRAY,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.DEVICE_REVISION: {
    // This property has been deprecated
    "property_id": MeshConfigServicePropertyID.DEVICE_REVISION,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 255,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.ERROR_STATUS: {
    // This property is unused
    "property_id": MeshConfigServicePropertyID.ERROR_STATUS,
    "property_size": 1,
    "default_value": 0, // SwitchErrorStatus value
    "min_value": 0,
    "max_value": 255,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 1,
  },
  MeshConfigServicePropertyID.DOUBLE_TAP_ENABLED: {
    "property_id": MeshConfigServicePropertyID.DOUBLE_TAP_ENABLED,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_DOUBLE_TAP_ENABLED,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.SWITCH_LOAD_TYPE: {
    "property_id": MeshConfigServicePropertyID.SWITCH_LOAD_TYPE,
    "property_size": 1,
    "default_value": bluetooth_common.SwitchLoadType.LOAD_TYPE_ONOFF,
    "min_value": 0,
    "max_value": 5,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_SWITCH_LOAD_TYPE,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.UNICAST_FORWARDING_GESTURES: {
    "property_id": MeshConfigServicePropertyID.UNICAST_FORWARDING_GESTURES,
    "property_size": 1,
    "default_value": 3,
    "min_value": 0,
    "max_value": 3,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_UNICAST_FORWARDING_GESTURES,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.CAPTOUCH_AND_LOAD_CONNECTED: {
    "property_id": MeshConfigServicePropertyID.CAPTOUCH_AND_LOAD_CONNECTED,
    "property_size": 1,
    "default_value": 1,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_CAPTOUCH_AND_LOAD_CONNECTED,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.AMPS_IN_MA: {
    "property_id": MeshConfigServicePropertyID.AMPS_IN_MA,
    "property_size": 2,
    "default_value": 0xFFFF,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.AMPS_SAFE_MAX_THRESHOLD: {
    "property_id": MeshConfigServicePropertyID.AMPS_SAFE_MAX_THRESHOLD,
    "property_size": 2,
    "default_value": 5500,
    "min_value": 0,
    "max_value": 65535,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_AMPS_SAFE_MAX_THRESHOLD,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.TEMP_SAFE_MAX_THRESHOLD: {
    "property_id": MeshConfigServicePropertyID.TEMP_SAFE_MAX_THRESHOLD,
    "property_size": 2,
    "default_value": 600,
    "min_value": -32768,
    "max_value": 32767,
    "property_type": bluetooth_common.MeshPropertyDataType.INT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_TEMP_SAFE_MAX_THRESHOLD,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.MOTION_MIN_SMPLS_BTW_UPDATE: {
    "property_id": MeshConfigServicePropertyID.MOTION_MIN_SMPLS_BTW_UPDATE,
    "property_size": 1,
    "default_value": 50,
    "min_value": 0,
    "max_value": 255,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_MOTION_MIN_SMPLS_BTW_UPDATE,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DBG_LAST_CS_RESULT_STATUS: {
    "property_id": MeshConfigServicePropertyID.DBG_LAST_CS_RESULT_STATUS,
    "property_size": 1,
    "default_value": 0xFF,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DBG_COMPUTED_ZERO_POINT: {
    "property_id": MeshConfigServicePropertyID.DBG_COMPUTED_ZERO_POINT,
    "property_size": 2,
    "default_value": 65535,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DBG_CYCLES_SINCE_ZC_SUCCESS: {
    "property_id": MeshConfigServicePropertyID.DBG_CYCLES_SINCE_ZC_SUCCESS,
    "property_size": 2,
    "default_value": 65535,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.TUNE_MAX_DEVIATION_IDL_ZERO: {
    "property_id": MeshConfigServicePropertyID.TUNE_MAX_DEVIATION_IDL_ZERO,
    "property_size": 2,
    "default_value": 32,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_TUNE_MAX_DEV_FROM_IDL_ZERO,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.TUNE_ZC_NUM_PT_FOR_NOISE_REDUCTION: {
    "property_id": MeshConfigServicePropertyID.TUNE_ZC_NUM_PT_FOR_NOISE_REDUCTION,
    "property_size": 2,
    "default_value": 15,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_TUNE_ZC_PTS_FOR_NOISE_RED,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.TUNE_MAX_DEV_BETWEEN_RUNS: {
    "property_id": MeshConfigServicePropertyID.TUNE_MAX_DEV_BETWEEN_RUNS,
    "property_size": 2,
    "default_value": 96,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_TUNE_MAX_DEV_BTW_RUNS,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.REBOOT: {
    "property_id": MeshConfigServicePropertyID.REBOOT,
    "property_size": 1,
    "default_value": 0,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.ENABLE_FWID_PACKET_BROADCAST: {
    "property_id": MeshConfigServicePropertyID.ENABLE_FWID_PACKET_BROADCAST,
    "default_value": 1,
    "property_size": 1,
    "default_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DFU_LAST_TRANSFER_STATE: {
    "property_id": MeshConfigServicePropertyID.DFU_LAST_TRANSFER_STATE,
    "property_size": 16,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8_ARRAY,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DFU_LAST_RX_RESPONSE: {
    "property_id": MeshConfigServicePropertyID.DFU_LAST_RX_RESPONSE,
    "default_value": 0,
    "property_size": 4,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT32,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DFU_END_TRANSFER_REASON: {
    "property_id": MeshConfigServicePropertyID.DFU_END_TRANSFER_REASON,
    "default_value": 0,
    "property_size": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DFU_LAST_RX_PACKET: {
    "property_id": MeshConfigServicePropertyID.DFU_LAST_RX_PACKET,
    "property_size": 20,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8_ARRAY,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.HARDWARE_REVISION: {
    "property_id": MeshConfigServicePropertyID.HARDWARE_REVISION,
    "property_size": 4,
    "default_value": 4294967295,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT32,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.CAPTOUCH_BTN00_TUNING_PARAM: {
    "property_id": MeshConfigServicePropertyID.CAPTOUCH_BTN00_TUNING_PARAM,
    "property_size": 15,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8_ARRAY,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_CAPTOUCH_BTN00_TUNING_PARAMS,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
    "array_default_value": [
      0x20, // BTN00 Conversion Count (lower byte)
      0x03, // BTN00 Conversion Count (upper byte)
      0x64, // BTN00 Conversion Gain (lower byte)
      0x00, // BTN00 Conversion Gain (upper byte)
      0x06, // BTN00 Proximity Threshold (lower byte)
      0x00, // BTN00 Proximity Threshold (upper byte)
      0x1E, // BTN00 Negative Touch Threshold (lower byte)
      0x00, // BTN00 Negative Touch Threshold (upper byte)
      0x03, // BTN00 Touch Debounce Threshold
      0x02, // BTN00 Count Filter Beta
      0x05, // BTN00 E00 Touch Threshold
      0x05, // BTN00 E01 Touch Threshold
      0x05, // BTN00 E02 Touch Threshold
      0x05, // BTN00 E03 Touch Threshold
      0x05  // BTN00 E04 Touch Threshold
    ],
  },
  MeshConfigServicePropertyID.CAPTOUCH_SLD00_TUNING_PARAM: {
    "property_id": MeshConfigServicePropertyID.CAPTOUCH_SLD00_TUNING_PARAM,
    "property_size": 13,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8_ARRAY,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_CAPTOUCH_SLD00_TUNING_PARAMS,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
    "array_default_value": [
      0x2C, // SLD00 Conversion Count (lower byte)
      0x01, // SLD00 Conversion Count (upper byte)
      0x64, // SLD00 Conversion Gain (lower byte)
      0x00, // SLD00 Conversion Gain (upper byte)
      0x02, // SLD00 Proximity Threshold (lower byte)
      0x00, // SLD00 Proximity Threshold (upper byte)
      0x1E, // SLD00 Negative Touch Threshold (lower byte)
      0x00, // SLD00 Negative Touch Threshold (upper byte)
      0x02, // SLD00 Touch Debounce Threshold
      0x01, // SLD00 Count Filter Beta
      0x02, // SLD00 E00 Touch Threshold
      0x02, // SLD00 E01 Touch Threshold
      0x02  // SLD00 E02 Touch Threshold
    ],
  },
  MeshConfigServicePropertyID.PROXY_HAS_ACTIVE_CONNS: {
    "property_id": MeshConfigServicePropertyID.PROXY_HAS_ACTIVE_CONNS,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.PROXY_DISCONNECT_ALL: {
    "property_id": MeshConfigServicePropertyID.PROXY_DISCONNECT_ALL,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.REPLAY_CACHE_CLEAR: {
    "property_id": MeshConfigServicePropertyID.REPLAY_CACHE_CLEAR,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.REPLAY_CACHE_GET_NUM_ELEM: {
    "property_id": MeshConfigServicePropertyID.REPLAY_CACHE_GET_NUM_ELEM,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 255,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.REPLAY_CACHE_GET_CUR_IV: {
    "property_id": MeshConfigServicePropertyID.REPLAY_CACHE_GET_CUR_IV,
    "property_size": 4,
    "default_value": 4294967295,
    "min_value": 0,
    "max_value": 4294967295,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT32,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.REPLAY_CACHE_SET_GET_ELEM_IDX: {
    "property_id": MeshConfigServicePropertyID.REPLAY_CACHE_SET_GET_ELEM_IDX,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 255,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.REPLAY_CACHE_GET_ELEM_SRC: {
    "property_id": MeshConfigServicePropertyID.REPLAY_CACHE_GET_ELEM_SRC,
    "property_size": 2,
    "default_value": 65535,
    "min_value": 0,
    "max_value": 65535,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.REPLAY_CACHE_GET_ELEM_SEQ: {
    "property_id": MeshConfigServicePropertyID.REPLAY_CACHE_GET_ELEM_SEQ,
    "property_size": 4,
    "default_value": 4294967295,
    "min_value": 0,
    "max_value": 4294967295,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT32,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.REPLAY_CACHE_GET_ELEM_IV: {
    "property_id": MeshConfigServicePropertyID.REPLAY_CACHE_GET_ELEM_IV,
    "property_size": 2,
    "default_value": 65535,
    "min_value": 0,
    "max_value": 65535,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DFU_RELAY_ENABLED: {
    "property_id": MeshConfigServicePropertyID.DFU_RELAY_ENABLED,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DFU_RELAY_APP_ID: {
    "property_id": MeshConfigServicePropertyID.DFU_RELAY_APP_ID,
    "property_size": 2,
    "default_value": 0,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT16,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DFU_RELAY_APP_VERSION: {
    "property_id": MeshConfigServicePropertyID.DFU_RELAY_APP_VERSION,
    "property_size": 4,
    "default_value": 0,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT32,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DBG_BUF_SET_NEXT_TRIGGER: {
    "property_id": MeshConfigServicePropertyID.DBG_BUF_SET_NEXT_TRIGGER,
    "property_size": 1,
    "default_value": 0,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DBG_BUF_AWAITING_NEXT_TRIGGER: {
    "property_id": MeshConfigServicePropertyID.DBG_BUF_AWAITING_NEXT_TRIGGER,
    "property_size": 1,
    "default_value": 0,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DBG_BUF_CUR_CONTENTS_TRIGGER: {
    "property_id": MeshConfigServicePropertyID.DBG_BUF_CUR_CONTENTS_TRIGGER,
    "property_size": 1,
    "default_value": 0,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DBG_BUF_SET_READ_CHUNK_IDX: {
    "property_id": MeshConfigServicePropertyID.DBG_BUF_SET_READ_CHUNK_IDX,
    "property_size": 1,
    "default_value": 0,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT8,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.DBG_BUF_GET_CHUNK: {
    "property_id": MeshConfigServicePropertyID.DBG_BUF_GET_CHUNK,
    "property_size": 8,
    "default_value": 0,
    "property_type": bluetooth_common.MeshPropertyDataType.UINT64,
    "flash_handle": bluetooth_common.FLASH_HANDLE_UNSET,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
  MeshConfigServicePropertyID.USE_COMPACT_COMM_PROTOCOL_FOR_PUBLISHING_VARIABLE: {
    "property_id": MeshConfigServicePropertyID.USE_COMPACT_COMM_PROTOCOL_FOR_PUBLISHING_VARIABLE,
    "property_size": 1,
    "default_value": 0,
    "min_value": 0,
    "max_value": 1,
    "property_type": bluetooth_common.MeshPropertyDataType.BOOL,
    "flash_handle": bluetooth_common.SwitchPropertyFlashHandle.FLASH_HANDLE_USE_COMPACT_COMM_PROTOCOL_FOR_PUBLISHING_VARIABLE,
    "publish_config_type": bluetooth_common.PublishConfigType.DISABLED,
    "deprecated": 0,
  },
}
