namespace py thrift_types.client_ui
namespace java thrift_types.client_ui

include "message_bus.thrift"

const string AUGUST_INTEGRATION_NAME = "August"
const string BUTTERFLYMX_INTEGRATION_NAME = "ButterflyMX"
const string ECOBEE_INTEGRATION_NAME = "Ecobee"
const string GENIE_INTEGRATION_NAME = "Genie"
const string HONEYWELL_INTEGRATION_NAME = "Honeywell"
const string HUE_INTEGRATION_NAME = "Hue"
const string LIFX_INTEGRATION_NAME = "LIFX"
const string NEST_INTEGRATION_NAME = "Nest"
const string RING_INTEGRATION_NAME = "Ring"
const string SCHLAGE_INTEGRATION_NAME = "Schlage Encode"
const string SMARTTHINGS_INTEGRATION_NAME = "SmartThings"
const string SOMFY_INTEGRATION_NAME = "Somfy"
const string SONOS_INTEGRATION_NAME = "Sonos"
const string TPLINK_INTEGRATION_NAME = "TP-Link Kasa"
const string WEMO_INTEGRATION_NAME = "Wemo"

const map<string, string> THIRDPARTY_VIRTUAL_DEVICE_IDENTIFIER_TO_INTEGRATION_NAME = {
		message_bus.AUGUST_IDENTIFIER: AUGUST_INTEGRATION_NAME,
		message_bus.BUTTERFLYMX_IDENTIFIER: BUTTERFLYMX_INTEGRATION_NAME,
		message_bus.ECOBEE_IDENTIFIER: ECOBEE_INTEGRATION_NAME,
		message_bus.GENIE_IDENTIFIER: GENIE_INTEGRATION_NAME,
		message_bus.HONEYWELL_IDENTIFIER: HONEYWELL_INTEGRATION_NAME,
		message_bus.HUE_BRIDGE_IDENTIFIER: HUE_INTEGRATION_NAME,
		message_bus.LIFX_IDENTIFIER: LIFX_INTEGRATION_NAME,
		message_bus.NEST_IDENTIFIER: NEST_INTEGRATION_NAME,
		message_bus.RING_VIRTUAL_DEVICE: RING_INTEGRATION_NAME,
		message_bus.SCHLAGE_IDENTIFIER: SCHLAGE_INTEGRATION_NAME,
		message_bus.SMARTTHINGS_IDENTIFIER: SMARTTHINGS_INTEGRATION_NAME,
		message_bus.SOMFY_IDENTIFIER: SOMFY_INTEGRATION_NAME,
		message_bus.SONOS_IDENTIFIER: SONOS_INTEGRATION_NAME,
		message_bus.TPLINK_IDENTIFIER: TPLINK_INTEGRATION_NAME,
		message_bus.WEMO_IDENTIFIER: WEMO_INTEGRATION_NAME,
}
