namespace py thrift_types.factory_programming
namespace java thrift_types.factory_programming

const string SINGLE_GANG_IMX6_FACEPLATE_PRODUCT_CODE_SUFFIX = "1"
const string MULTI_GANG_IMX6_FACEPLATE_PRODUCT_CODE_SUFFIX = "2"
const string SINGLE_GANG_I350_FACEPLATE_PRODUCT_CODE_SUFFIX = "3"
const string MULTI_GANG_I350_FACEPLATE_PRODUCT_CODE_SUFFIX = "4"

const set<string> IMX6_FACEPLATE_PRODUCT_CODE_SUFFIXES = [
    SINGLE_GANG_IMX6_FACEPLATE_PRODUCT_CODE_SUFFIX,
    MULTI_GANG_IMX6_FACEPLATE_PRODUCT_CODE_SUFFIX,
]
const set<string> I350_FACEPLATE_PRODUCT_CODE_SUFFIXES = [
    SINGLE_GANG_I350_FACEPLATE_PRODUCT_CODE_SUFFIX,
    MULTI_GANG_I350_FACEPLATE_PRODUCT_CODE_SUFFIX,
]

const string BRILLIANT_VENDOR_FACTORY_CODE = "BA" # Used when flashing controls internally
const set<string> VTECH_VENDOR_FACTORY_CODES = ["VD", "VJ"]
