# Uncomment the next line to define a global platform for your project
platform :ios, '14'

target 'BRLTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BRLTest
  pod 'BRL', :path => 'local-pods/BRL'
  pod 'Thrift', :git=> 'git@github.com:ramjet-labs/Thrift-Swift.git', :branch => "brilliant-dev"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('14.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
