# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BRLTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BRLTest
  pod 'BRL', :path => 'local-pods/BRL'
  pod 'Thrift', :git=> 'git@github.com:ramjet-labs/Thrift-Swift.git', :branch => "brilliant-dev"
end
